#users
User.create(name: "Brad", favorite_movie: "The Big Lebowski", gif_that_represents_you: "https://media.giphy.com/media/hcd9ZPh0sb3IA/giphy.gif")
User.create(name: "Barbara", favorite_movie: "Snatch", gif_that_represents_you: "https://media.giphy.com/media/dvDCHPFnxnYubsrNvl/giphy.gif")
User.create(name: "Yoan", favorite_movie: "Back to the Future", gif_that_represents_you: "https://media.giphy.com/media/xT1XGzXhVgWRLN1Cco/giphy.gif")
User.create(name: "Tony", favorite_movie: "Ferris Bueller's Day Off", gif_that_represents_you: "https://media.giphy.com/media/xT9IgzoKnwFNmISR8I/giphy.gif")

#questions
Question.create(title: "Star Wars", genre: "Science Fiction", first_gif: "https://media.giphy.com/media/3o7buijTqhjxjbEqjK/giphy.gif", second_gif: "http://giphygifs.s3.amazonaws.com/media/9umH7yTO8gLYY/giphy.gif")
Question.create(title: "Singing in the Rain", genre: "Musical", first_gif: "https://media.giphy.com/media/143qWPF33HtSTK/giphy.gif", second_gif: "https://media.giphy.com/media/1Yfxps0AHRYBR2tK2G/giphy.gif")
Question.create(title: "Citizen Kane", genre: "Drama", first_gif: "https://media.giphy.com/media/5ME9j9hbSJYrK/giphy.gif", second_gif: "https://media.giphy.com/media/LXjFLBeyIzXUs/giphy.gif")
Question.create(title: "Casablanca", genre: "Drama", first_gif: "https://media.giphy.com/media/l2SpVMDEIJvjwavwQ/giphy.gif", second_gif: "https://media.giphy.com/media/xTdAjr0aZ8PcSAGTqE/giphy.gif")
Question.create(title: "The Rocky Horror Picture Show", genre: "Musical", first_gif: "https://media.giphy.com/media/26tPcgtbhhbU88U2A/giphy.gif", second_gif: "https://media.giphy.com/media/zXeX29w6jxjAk/giphy.gif")
Question.create(title: "The Breakfast Club", genre: "Dramedy", first_gif: "http://giphygifs.s3.amazonaws.com/media/AwyW3bCYArhbG/giphy.gif", second_gif: "https://media.giphy.com/media/26uf7O2zb8HweaHNC/giphy.gif")
Question.create(title: "The Godfather", genre: "Drama", first_gif: "http://giphygifs.s3.amazonaws.com/media/FZaNpQrCtyQms/giphy.gif", second_gif: "http://giphygifs.s3.amazonaws.com/media/GKbfzvrxr5jW0/giphy.gif")
Question.create(title: "Mean Girls", genre: "Comedy", first_gif: "https://media.giphy.com/media/xThuW9zh3xNc4uGbu0/giphy.gif", second_gif: "https://media.giphy.com/media/dvDCHPFnxnYubsrNvl/giphy.gif")
Question.create(title: "Napoleon Dynamite", genre: "Comedy", first_gif: "https://media.giphy.com/media/SsrDV8i0LSFxGHpzTq/giphy.gif", second_gif: "https://media.giphy.com/media/xUOxeXt41UOYRusw4E/giphy.gif")
Question.create(title: "A Clockwork Orange", genre: "Drama", first_gif: "https://media.giphy.com/media/3o6MbhEln7WjAKiqkM/giphy.gif", second_gif: "https://media.giphy.com/media/3o7TKPdUkkbCAVqWk0/giphy.gif")
Question.create(title: "The Lord of the Rings", genre: "Fantasy", first_gif: "http://giphygifs.s3.amazonaws.com/media/poF4AwItROabe/giphy.gif", second_gif: "https://media.giphy.com/media/p5LNTI575vmow/giphy.gif")
Question.create(title: "Taxi Driver", genre: "Drama", first_gif: "https://media.giphy.com/media/3oFzmrP8ZDnNZxsyFW/giphy.gif", second_gif: "https://media.giphy.com/media/mIMsLsQTJzAn6/giphy.gif")
Question.create(title: "Fight Club", genre: "Drama", first_gif: "http://giphygifs.s3.amazonaws.com/media/rcRwO8GMSfNV6/giphy.gif", second_gif: "https://media.giphy.com/media/l41JUhcCreHloiiru/giphy.gif")
Question.create(title: "Reservoir Dogs", genre: "Drama", first_gif: "https://media.giphy.com/media/NqXnptJhHoWTS/giphy.gif", second_gif: "https://media.giphy.com/media/kBZBlLVlfECvOQAVno/giphy.gif")
Question.create(title: "Office Space", genre: "Comedy", first_gif: "https://media.giphy.com/media/9oF7EAvaFUOEU/giphy.gif", second_gif: "https://media.giphy.com/media/xT9IgusfDcqpPFzjdS/giphy.gif")
Question.create(title: "Anchorman", genre: "Comedy", first_gif: "http://giphygifs.s3.amazonaws.com/media/1e2RyYMVRCE1y/giphy.gif", second_gif: "https://media.giphy.com/media/dsQrzqmtwYnobTQBDW/giphy.gif")
Question.create(title: "Groundhog Day", genre: "Comedy", first_gif: "https://media.giphy.com/media/lNUCXNHGH7Gog/giphy.gif", second_gif: "https://media.giphy.com/media/3ROGCp62zakRW/giphy.gif")
Question.create(title: "Wayne's World", genre: "Comedy", first_gif: "https://media.giphy.com/media/l41lZccR1oUigYeNa/giphy.gif", second_gif: "https://media.giphy.com/media/euwvytHJqMG21wSkI4/giphy.gif")
Question.create(title: "Home Alone", genre: "Comedy", first_gif: "https://media.giphy.com/media/l0IylQoMkcbZUbtKw/giphy.gif", second_gif: "https://media.giphy.com/media/gKW26O7cU2JDG/giphy.gif")
Question.create(title: "School of Rock", genre: "Comedy", first_gif: "https://media.giphy.com/media/j39AzlvlJqE7e/giphy.gif", second_gif: "https://media.giphy.com/media/QLvRBqfLXCphu/giphy.gif")
Question.create(title: "Star Trek", genre: "Science Fiction", first_gif: "https://media.giphy.com/media/l1J3rGigrYfx8aKqI/giphy.gif", second_gif: "https://media.giphy.com/media/QM8d5Zx9G5gLhDNJYc/giphy.gif")
Question.create(title: "Jurassic Park", genre: "Science Fiction", first_gif: "https://media.giphy.com/media/qN9x0UIc0Rhg4/giphy.gif", second_gif: "https://media.giphy.com/media/l378esHHoBQ8S9c9a/giphy.gif")
Question.create(title: "Blade Runner", genre: "Science Fiction", first_gif: "https://media.giphy.com/media/1ludrxHRnUmT6/giphy.gif", second_gif: "https://media.giphy.com/media/l0HlLlCU434c3egNy/giphy.gif")
Question.create(title: "RoboCop", genre: "Science Fiction", first_gif: "https://media.giphy.com/media/tczJoRU7XwBS8/giphy.gif", second_gif: "https://media.giphy.com/media/81xwEHX23zhvy/giphy.gif")
Question.create(title: "Back to the Future", genre: "Science Fiction", first_gif: "https://media.giphy.com/media/dXjQIUyWbkQPSVidcF/giphy.gif", second_gif: "https://media.giphy.com/media/ywdAIxqBkyXHq/giphy.gif")
Question.create(title: "The Little Mermaid", genre: "Animated", first_gif: "https://media.giphy.com/media/1URktmTTAIflh6VLUL/giphy.gif", second_gif: "https://media.giphy.com/media/yrNBsUzUm2Eyk/giphy.gif")
Question.create(title: "Toy Story", genre: "Animated", first_gif: "https://media.giphy.com/media/12ttoBXEqixfmo/giphy.gif", second_gif: "https://media.giphy.com/media/WoWm8YzFQJg5i/giphy.gif")
Question.create(title: "The Lion King", genre: "Animated", first_gif: "https://media.giphy.com/media/ZkBcyGcNwNUUU/giphy.gif", second_gif: "https://media.giphy.com/media/eoN5fHRfV4sSI/giphy.gif")
Question.create(title: "Chicken Run", genre: "Animated", first_gif: "https://media.giphy.com/media/Zg7clvqHE3CdW/giphy.gif", second_gif: "https://media.giphy.com/media/7kn27lnYSAE9O/giphy.gif")
Question.create(title: "The Nightmare Before Christmas", genre: "Animated", first_gif: "https://media.giphy.com/media/KFOqUTRI8H26s/giphy.gif", second_gif: "https://media.giphy.com/media/MrxXXBriEIKBO/giphy.gif")

# #Games
# Game.create(user_id: 1)
# Game.create(user_id:1) 

# #Game 1
# GameQuestion.create(question_id: 1, game_id: 1, correct: true)
# GameQuestion.create(question_id: 2, game_id: 1, correct: true)
# GameQuestion.create(question_id: 3, game_id: 1, correct: true)
# GameQuestion.create(question_id: 4, game_id: 1, correct: true)
# GameQuestion.create(question_id: 5, game_id: 1, correct: true)
# GameQuestion.create(question_id: 6, game_id: 1, correct: true)
# GameQuestion.create(question_id: 7, game_id: 1, correct: true)
# GameQuestion.create(question_id: 8, game_id: 1, correct: true)
# GameQuestion.create(question_id: 9, game_id: 1, correct: true)
# GameQuestion.create(question_id: 10, game_id: 1, correct: true)

# #Game 2
# GameQuestion.create(question_id: 11, game_id: 2, correct: true)
# GameQuestion.create(question_id: 12, game_id: 2, correct: false)
# GameQuestion.create(question_id: 13, game_id: 2, correct: false)
# GameQuestion.create(question_id: 14, game_id: 2, correct: false)
# GameQuestion.create(question_id: 15, game_id: 2, correct: false)
# GameQuestion.create(question_id: 16, game_id: 2, correct: false)
# GameQuestion.create(question_id: 17, game_id: 2, correct: false)
# GameQuestion.create(question_id: 18, game_id: 2, correct: false)
# GameQuestion.create(question_id: 19, game_id: 2, correct: false)
# GameQuestion.create(question_id: 20, game_id: 2, correct: false)

# #Game 3: Sci-Fi
# GameQuestion.create(question_id: 21, game_id: 3, correct: true)

